### ISSUE TITLE
Namespace change

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/publisher#159]
@caouecs, hi!

I decided to push my repository to the organization. In the near future I will prepare changes to the package name and namespace.

I need your help now. I do not have access to the settings of this repository. Can you change the name of the project from `laravel-lang-publisher` to `publisher`?

**Comment by andrey-helldar** [comment]
@caouecs, and one more thing: can you add a new project to [packagist](https://packagist.org/packages/submit) after you rename this repository?

I changed the project name for this, but I am not authorized.

**Comment by caouecs** [comment]
done

**Comment by andrey-helldar** [comment]
Thank you!
