### ISSUE TITLE
[V11] Remove keys and empty files

### ISSUE THREAD

**Issue by mohamedsabil83** [Laravel-Lang/publisher#187]
- Lang Publisher Version: 11.1.6
- Laravel Version: 8.74
- PHP Version: 8.0

### Description:
I'm using Arabic locale. After upgrading to v11.1.6 from v10:

- When run `php artisan lang:update` the following keys deleted from the **validation** file (accepted_if, declined, declined_if, prohibits). Also, the **attributes** array became empty.

- When adding any locale, e.g. **fr**, the package publishes the files with an empty array as content.

**Comment by andrey-helldar** [comment]
Fixed in the [`11.1.7`](https://github.com/Laravel-Lang/publisher/releases/tag/v11.1.7) version.

Thank you!

**Comment by mohamedsabil83** [comment]
Thank you for the quick fix.

I forgot to say that some phrases were removed from the **json** file like some shown in the image. Is it a bug or a new approach when publishing locales?

![Screenshot from 2021-12-07 02-10-43](https://user-images.githubusercontent.com/10126040/144937531-a0f4c44d-d40a-446b-9a34-e40141edb932.png)

**Comment by andrey-helldar** [comment]
You're welcome!

The removed translations are specific to Laravel Nova.

For example, 

![image](https://user-images.githubusercontent.com/10347617/144938100-11ce0326-c154-42ae-9d16-7b76025c728a.png)

If it is not installed in the project, then these keys will not be installed in the application.

**Comment by andrey-helldar** [comment]
If your application uses many of the keys to be installed, then you can create a new package using [this template](https://github.com/Laravel-Lang/translations-template) and specify everything you need in it.

**Comment by mohamedsabil83** [comment]
I see. It's ok with me just asking to be sure if that just the reason.

Thank u again for your hard work 👍🏽
