### ISSUE TITLE
Why "lang:add" always implicitly includes en?

### ISSUE THREAD

**Issue by sergiz** [Laravel-Lang/publisher#192]
- Lang Publisher Version: 11.1.9
- Laravel Version: 8.73.2
- PHP Version: 7.4.10

### Description:
When I run `php artisan lang:add de`, it also overwrites my `en` files. Shouldn't it only add `de` in this case?

### Steps To Reproduce:

1. Run `php artisan lang:add de`
2. See your `en` files getting overwritten

**Comment by andrey-helldar** [comment]
That's right, in your case a new localization should be added. Existing localizations should not be changed.

I will fix this bug shortly.

**Comment by andrey-helldar** [comment]
Fixed in the [`v11.1.10`](https://github.com/Laravel-Lang/publisher/releases/tag/v11.1.10).

Thank you!
