### ISSUE TITLE
Alignment = false still removes comments

### ISSUE THREAD

**Issue by sergiz** [Laravel-Lang/publisher#193]
- Lang Publisher Version: 11.1.9
- Laravel Version: 8.73.2
- PHP Version: 7.4.10

### Description:
Considering the documentation (https://laravel-lang.github.io/publisher/features/alignment.html), I understand that if you disable alignment, then the comments should stay. Or why would that section even talk about comments being removed?

### Steps To Reproduce:
1. Set `'alignment' => false,` in the config file
2. Get comments still removed from the translation files

**Comment by andrey-helldar** [comment]
No, comments are always deleted, since the php array does not provide for storing comments.
