### ISSUE TITLE
How to install a localization from laravel-lang/lang ?

### ISSUE THREAD

**Issue by realtebo** [Laravel-Lang/publisher#200]
- Lang Publisher Version: 11.1.5
- Laravel Version: 8.79.0
- PHP Version: 7.4

### Description:

How to install italian locale? 

I have installed both

        "laravel-lang/lang": "~8.0",
        "laravel-lang/publisher": "^11.1",

I want to simply install/expose/use italian localizations

I am not able to do understand how to do

### Steps To Reproduce:

I also tried a `locale:add it` but it creates new empty file for italian locales

I tried also running `locale:update` but nothing changes

**Comment by realtebo** [comment]
I tried also running `locale:update` but nothing changes

**Comment by mohamedsabil83** [comment]
Don't install both of them as **laravel-lang/publisher** install the proper version of **laravel-lang/lang** under the hood. maybe that causes the issue.
try to remove **laravel-lang/lang**

**Comment by realtebo** [comment]
I read in the doc here:; https://laravel-lang.github.io/publisher/using/plugins/index.html 

> Install the package into your application. For example, composer require laravel-lang/lang --dev

I removed vendor
I removed explicit dev dependency of laravel-lang/lang
I run composer:upgrade

Installed these 
> Downloading laravel-lang/lang (10.1.12)
> Downloading laravel-lang/publisher (v11.1.12)

I run `php artisan locale:add it`

**It worked**

There is something wrong in the `laravel-lang/lang` installation instructions.

**Comment by andrey-helldar** [comment]
@realtebo, I'll update the documentation soon :)

**Comment by andrey-helldar** [comment]
@realtebo, I'll update the documentation soon :)

The https://laravel-lang.github.io/lang/installation/composer.html documentation describes the installation process without a publisher

**Comment by realtebo** [comment]
It could be usefull to say: install THEN manually copy files :)

**Comment by andrey-helldar** [comment]
@realtebo, in version [`11.1.5`](https://github.com/Laravel-Lang/publisher/blob/v11.1.5/composer.json#L38-L47) I wanted to remove the `lang` package from the publisher, but in patch [`11.1.6`](https://github.com/Laravel-Lang/publisher/blob/v11.1.6/composer.json#L38-L47) I brought it back.

Just run `composer update`.

**Comment by andrey-helldar** [comment]
> It could be usefull to say: install THEN manually copy files :)

https://laravel-lang.github.io/lang/installation/files.html :)

**Comment by realtebo** [comment]
Please, don't hate me. It's only that install in the 'list' mode tells user that must choose one of 4 methods 

nothing helps user to understand that AFTER installing using composer/github/svn must always copy files. 
I suggest to replace the list and 5 pages with a more clear and simple paragraph. Just and idea.

**Comment by andrey-helldar** [comment]
I agree
