### ISSUE TITLE
Publisher doesn't detect Jetstream Translations in Laravel 10

### ISSUE THREAD

**Issue by luisprmat** [Laravel-Lang/publisher#321]
### Environment

- Laravel-Lang Publisher Version: 14.6.1
- Laravel Version: 10.0.0
- PHP Version: 8.2.2

### Issue description

@andrey-helldar In Laravel 9 it was detected if jetstream was installed and the translations were added, in Laravel 10 only the framework translations are added, that is, it is not working

![image](https://user-images.githubusercontent.com/9275870/218867611-85ec079d-510a-46b9-8ba3-03c793d6462e.png)

There may also be bugs with breeze or other packages

### Steps to reproduce

- `laravel new project --jet`
- Choose `livewire` stack (also i choose `phpunit`)
- Set language:
    - Change `config.app.locale` to `es`
    - Run `composer require laravel-lang/publisher laravel-lang/lang laravel-lang/attributes --dev`
    - Run `php artisan lang:add es`

*Result*
Spanish translations for Jetstream Views weren't added.

**Comment by andrey-helldar** [comment]
I understood the reason. I'll do it now :)

![image](https://user-images.githubusercontent.com/10347617/218871739-64c76564-dece-4c14-8b44-04079f19a3cb.png)

**Comment by andrey-helldar** [comment]
`laravel-lang/lang` 12.17.0 is released: https://github.com/Laravel-Lang/lang/releases/tag/12.17.0

Also, you can replace a `composer require laravel-lang/publisher laravel-lang/lang laravel-lang/attributes --dev` command with `composer require laravel-lang/common --dev` 🙂
