### ISSUE TITLE
Docs throw 404

### ISSUE THREAD

**Issue by pxlrbt** [Laravel-Lang/publisher#324]
### Environment

Browser

### Issue description

In think publisher docs were merged into package docs, but the subdomain throws a 404 now.

### Steps to reproduce

Go to https://publisher.laravel-lang.com/

**Comment by andrey-helldar** [comment]
@pxlrbt, a few days ago we combined the documentation for all our projects and posted it here: https://laravel-lang.com

You can say where you found the `publisher.laravel-lang.com` address so that we can try to update it?

**Comment by andrey-helldar** [comment]
I also added a 301 redirect to the new address. Now, when you try to go to the old address, the browser will automatically go to the new site.

Thanks for your feedback!

**Comment by pxlrbt** [comment]
> I also added a 301 redirect to the new address. Now, when you try to go to the old address, the browser will automatically go to the new site.

Sweet, thanks. It was still listed on Google, so you were lost when coming from there.
I didn't notice the change and was looking for the Publisher docs.

Good move though. I always struggled a bit to get from Laravel-Lang to the publisher docs 😅

**Comment by andrey-helldar** [comment]
Thank you!

Yes, these were different projects in different visibility zones, but later we combined them into one place. And now, the documentation has been updated 🙂

By the way, you may also be interested in the [`laravel-lang/common`](https://github.com/Laravel-Lang/common) project. Its task is to simplify the [`installation`](https://laravel-lang.com/installation/#recommended) of all the necessary packages.

![image](https://user-images.githubusercontent.com/10347617/222481947-0100199e-d0a4-4b7f-8853-c7dce89330cf.png)

Compatibility table: https://laravel-lang.com/installation/compatibility/common.html
