### ISSUE TITLE
Wrong upper and lowercases in replaced attributes

### ISSUE THREAD

**Issue by renky** [Laravel-Lang/publisher#325]
### Environment

- Laravel-Lang Version: 3.1.1
- Laravel Version: 10.2.0
- PHP Version: 8.2

### Issue description

Email-Validation with a wrong email leads to the following error message in German:
"E-mail-adresse muss eine gültige E-Mail-Adresse sein."
As visible the first automatically replaced "E-mail-adresse" has the wrong casing - should be written like the latter "E-Mail-Adresse" with upper cases.

In older versions of laravel-lang the attributes have been replaced with ":attribute" and correct casing in the validation.php attribute list 'email' => 'E-Mail-Adresse'. In the current version it is done with ":Attribute" and 'email' => 'e-mail-adresse', what finally results in the capital first letter (which I guess is a laravel feature thats not documented?!)

The question is now: is it a Bug in laravel-lang, or in laravels localization feature? For all other attributes this migth be ok, but I guess there are more cases where a dash is used!?

Since the official laravel installation doesn't use :attribute I'd prefer the old solution...

### Steps to reproduce

just validate with german translation file

**Comment by renky** [comment]
Ok, got it - then in fact this was "broken" when switching to the new structure 9 months ago... in the old validation.php files all attributes had capital letters - maybe this was done by a script? In meanwhile a few arguments have already been fixed but not all...

**Comment by andrey-helldar** [comment]
Indeed, I did not pay attention to it. My apologies.

I updated the values to match the previous version and [`released`](https://github.com/Laravel-Lang/attributes/releases/tag/v2.3.1) the hotfix. Update the dependencies with the `composer update` command and check again. Everything should be right now.

Thanks for the help!

**Comment by renky** [comment]
Thanks 👍
