### ISSUE TITLE
Add files from a custom plugin

### ISSUE THREAD

**Issue by forxer** [Laravel-Lang/publisher#326]
### Environment

Note: this is not a "bug" but when I click on "Questions & Other" there is a 404 error

- Laravel-Lang Publisher Version: 14.6.2
- Laravel Version: 10.5.1
- PHP Version: 8.2.4

### Issue description

I've try to create a plugin for the common language terms i use in my applications "[Generic term translations for Laravel](https://github.com/forxer/generic-term-translations-for-laravel)"

But when I add the files through the publisher, they are well copied, but contain empty arrays.

I only used PHP files whether in the "source" and "locales" directories.

I wonder if it's the absence of a .json file that causes this or just an oversight on my part or a bad way of doing it.

Maybe there is a plugin development tool to generate the necessary, I know there is the plugin template but I want to start from scratch to better understand the mechanisms.

### Steps to reproduce

Install the package:

```
composer require forxer/generic-term-translations-for-laravel --dev
```

Run:

```
 php artisan lang:update
```

Ps: I had already installed before laravel-lang/common

**Comment by andrey-helldar** [comment]
I also noticed that the files in the src/locales folder are placed incorrectly.

A feature of our project is that it can simultaneously contain keys from different versions of the project and check for uniqueness. That is, by translating once, the translation will automatically be used wherever it is called.

What should be done:

1. Run the console command `vendor/bin/lang sync` from the Foo project folder.
2. You will find the file "src/locales/{locale}/php.json" containing all keys for translations from all php files of the source folder
3. Translate this file manually or call the `vendor/bin/lang translate` command to invoke the machine translation function.
4. Remove PHP files from `src/locale/` folders
5. Commit and publish the release.

**Comment by forxer** [comment]
Ok i've moved the two folder, and it correctly publishe files and data.

However, I don't have a /vendor/bin/lang file.

**Comment by andrey-helldar** [comment]
This command is available if, in the `forxer/generic-term-translations-for-laravel` project, go to the console and execute `composer update`. It comes with the `laravel-lang/status-generator` package, which is listed in your dev dependencies.

**Comment by andrey-helldar** [comment]
You can also post a link to your project [here](https://laravel-lang.com/plugins/community.html).

**Comment by forxer** [comment]
I'll try to add some documentation and I'll do that. Thanks again.

**Comment by andrey-helldar** [comment]
You're welcome!
